apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: offer-tool-web-clb-deployment
    qcloud-app: offer-tool-web-clb-deployment
  name: offer-tool-web-clb-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: offer-tool-web-clb-deployment
      qcloud-app: offer-tool-web-clb-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: offer-tool-web-clb-deployment
        qcloud-app: offer-tool-web-clb-deployment
    spec:
      containers:
      - env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: NGINX_VERSION
          value: 1.22.0
        - name: NJS_VERSION
          value: 0.7.4
        - name: PKG_RELEASE
          value: "1"
        image: ccr.ccs.tencentyun.com/offer_tool/web:latest
        imagePullPolicy: Always
        name: offer-tool
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
