apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: offer-tool-web-clb-deployment
    qcloud-app: offer-tool-web-clb-deployment
  name: offer-tool-web-clb-deployment
  namespace: default
spec:
  clusterIP: 172.18.255.49
  clusterIPs:
  - 172.18.255.49
  externalTrafficPolicy: Cluster
  ports:
  - name: 80-80-tcp
    nodePort: 30705
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: offer-tool-web-clb-deployment
    qcloud-app: offer-tool-web-clb-deployment
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 1.15.160.13
